[server]
enableStaticServing = true
maxUploadSize = 200
enableCORS = false

[theme]
primaryColor = "#2e8b57"  # Forest Green
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f8ff"  # AliceBlue
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"

[deprecation]
showPyplotGlobalUse = false
